# Build Python Workflow
# 
# Based on Starter Workflow Here
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow
#
# Assumes an empty branch named `badges` is present. 
# https://stackoverflow.com/a/34100189

# Workflow name
name: Build Python

# Run only on pushes and pull requests on main branch, as well as tags
# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:    
      - main

# Define a single job named build
jobs:
  build:

    # Run job on Ubuntu runner
    runs-on: ubuntu-latest

    # Job Steps
    steps:

      # Step 1 - Checkout the Repository
      # https://github.com/actions/checkout
      - name: 1 - Checkout Repository
        uses: actions/checkout@v2
      
      # Step 2 - Set up Python 3
      # https://github.com/actions/setup-python
      - name: 2- Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'     # Version range or exact version of a Python version to use
          architecture: 'x64'       # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'              # cache pip requirements

      # Step 3 - Install Dependencies
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#requirements-file
      - name: 3 - Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4 - Run Tox
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#running-tests-with-tox
      - name: 4 - Run Tox
        run: tox -e py

      # Step 5A - Publish Test Reports
      # https://github.com/marketplace/actions/junit-report-action
      - name: 5A - Publish Test Reports
        uses: mikepenz/action-junit-report@v2
        if: always()                # always run even if the previous step fails
        with:
          report_paths: |
            reports/mypy/mypy.xml
            reports/pytest/pytest.xml
      
      # Step 5B - Run Flake8 and Publish Annotations
      # https://github.com/reviewdog/action-flake8
      - name: 5B - Run Flake8 and Publish Annotations
        uses: reviewdog/action-flake8@v3
        if: always()                # always run even if the previous step fails
        with:
          flake8_args: --docstring-convention google
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
      
      # ----------------------------------------------------------
      # THESE ONLY RUN IF BUILD SUCCEEDS
      # ----------------------------------------------------------

      # Step 6 - Save Files from Build
      # https://github.com/actions/upload-artifact
      - name: 6 - Archive Build Files
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/*

      # Step 7 - Generate Coverage Badges
      # https://github.com/action-badges/cobertura-coverage-xml-badges
      - name: 7 - Generate Coverage Badges
        uses: action-badges/cobertura-coverage-xml-badges@0.2.1
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./reports/coverage/coverage.xml

      # ----------------------------------------------------------
      # THESE ONLY RUN IF NEW TAG IS PUSHED - WILL CREATE RELEASE
      # ----------------------------------------------------------

      # Step 8 - Deploy PDoc to GitHub Pages
      # https://github.com/JamesIves/github-pages-deploy-action
      - name: 8 - Deploy PDoc
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          branch: gh-pages                  # The branch the action should deploy to
          folder: ./reports/doc/cc410/      # The folder the action should deploy
      
      # Step 9 - Make Release on GitHub
      # https://github.com/softprops/action-gh-release
      - name: 9 - Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*